void init_flags();
void unque_init();

extern UINT8 tnum_rcv_unq_norm ;
extern UINT8 tnum_rcv_unq_zero ;
extern UINT8 tnum_rcv_unq_dyna ;
extern UINT8 tnum_rcv_que_norm ;
extern UINT8 tnum_snd_in_norm ;
extern UINT8 tnum_snd_in_zero ;
extern UINT8 tnum_snd_ex_trig_norm ;
extern UINT8 tnum_snd_ex_pend_norm ;
extern UINT8 tnum_snd_ex_trig_zero ;
extern UINT8 tnum_snd_ex_trig_dyna ;
extern UINT8 tnum_snd_ex_pend_dyna ;
extern UINT8 tnum_rcv_ipdu_norm ;
extern UINT8 tnum_rcv_ipdu_zero ;
extern UINT8 tnum_rcv_ipdu_dyna ;
extern UINT8 tnum_que_elem[];
extern ApplicationDataRef msgbuf_rcv_unq_norm[];
extern UINT32 msgsize_rcv_unq_norm[];
extern ApplicationDataRef msgbuf_rcv_unq_zero[];
extern ApplicationDataRef msgbuf_rcv_unq_dyna[];
extern UINT32 msgsize_rcv_unq_dyna[];
extern LengthRef msglength_rcv_unq_dyna[];
extern ApplicationDataRef msgbuf_head_que_norm[];
extern ApplicationDataRef msgbuf_end_que_norm[];
extern UINT32 msgsize_que_norm[];
extern UINT8 msgque_cnt[];
extern ApplicationDataRef msgque_get_addr[];
extern ApplicationDataRef msgque_put_addr[];
extern UINT32 msgsize_snd_ex_trig_dyna[];
extern UINT32 msgsize_snd_ex_pend_dyna[];
extern const COPYFP copyfunc_rcv_unq_norm[];
extern const COPYFP copyfunc_rcv_que_norm[];
extern const COPYFP copyfunc_snd_ex_trig_norm[];
extern const COPYFP copyfunc_snd_ex_pend_norm[];
extern UINT8 msgsize_snd_ex_trig_norm[];
extern UINT8 msgsize_snd_ex_pend_norm[];
extern const FILTFP filter_rcv_unq_norm[];
extern const FILTFP filter_init_rcv_unq_norm[];
extern const FILTFP filter_rcv_que_norm[];
extern const FILTFP filter_init_rcv_que_norm[];
extern const FILTFP filter_snd_ex_trig_norm[];
extern const FILTFP filter_init_snd_ex_trig_norm[];
extern const FILTFP filter_snd_ex_pend_norm[];
extern const FILTFP filter_init_snd_ex_pend_norm[];
extern UINT64 initialvalue_rcv_unq_norm[];
extern UINT64 initialvalue_rcv_unq_dyna[];
extern UINT64 initialvalue_rcv_que_norm[];
extern UINT64 initialvalue_snd_ex_trig_norm[];
extern UINT64 initialvalue_snd_ex_pend_norm[];
extern UINT64 initialvalue_snd_ex_trig_dyna[];
extern UINT64 initialvalue_snd_ex_pend_dyna[];
extern UINT8 byteorder_snd_ex_trig_norm[];
extern UINT8 byteorder_snd_ex_pend_norm[];
extern IPDUType ipduid_snd_ex_trig_norm[];
extern UINT32 bitsize_snd_ex_trig_norm[];
extern UINT32 offset_snd_ex_trig_norm[];
extern IPDUType ipduid_snd_ex_pend_norm[];
extern UINT32 bitsize_snd_ex_pend_norm[];
extern UINT32 offset_snd_ex_pend_norm[];
extern IPDUType ipduid_snd_ex_trig_zero[];
extern IPDUType ipduid_snd_ex_trig_dyna[];
extern UINT32 offset_snd_ex_trig_dyna[];
extern UINT32 bitsize_snd_ex_trig_dyna[];
extern IPDUType ipduid_snd_ex_pend_dyna[];
extern UINT32 offset_snd_ex_pend_dyna[];
extern UINT32 bitsize_snd_ex_pend_dyna[];
extern const FP notification1_rcv_unq_norm[];
extern const FP notification1_rcv_unq_zero[];
extern const FP notification1_rcv_unq_dyna[];
extern const FP notification1_rcv_que_norm[];
extern const FP notification2_snd_ex_trig_norm[];
extern const FP notification2_snd_ex_pend_norm[];
extern const FP notification2_snd_ex_trig_zero[];
extern const FP notification2_snd_ex_trig_dyna[];
extern const FP notification2_snd_ex_pend_dyna[];
extern const FP notification3_rcv_unq_norm[];
extern const FP notification3_rcv_unq_zero[];
extern const FP notification3_rcv_unq_dyna[];
extern const FP notification3_rcv_que_norm[];
extern const FP notification4_snd_ex_trig_norm[];
extern const FP notification4_snd_ex_pend_norm[];
extern const FP notification4_snd_ex_trig_zero[];
extern const FP notification4_snd_ex_trig_dyna[];
extern const FP notification4_snd_ex_pend_dyna[];
extern const FP resetflag1_rcv_unq_norm[];
extern const FP resetflag1_rcv_unq_zero[];
extern const FP resetflag1_rcv_unq_dyna[];
extern const FP resetflag1_rcv_que_norm[];
extern const FP resetflag2_snd_ex_trig_norm[];
extern const FP resetflag2_snd_ex_pend_norm[];
extern const FP resetflag2_snd_ex_trig_zero[];
extern const FP resetflag2_snd_ex_trig_dyna[];
extern const FP resetflag2_snd_ex_pend_dyna[];
extern const FP resetflag3_rcv_unq_norm[];
extern const FP resetflag3_rcv_unq_zero[];
extern const FP resetflag3_rcv_unq_dyna[];
extern const FP resetflag3_rcv_que_norm[];
extern const FP resetflag4_snd_ex_trig_norm[];
extern const FP resetflag4_snd_ex_pend_norm[];
extern const FP resetflag4_snd_ex_trig_zero[];
extern const FP resetflag4_snd_ex_trig_dyna[];
extern const FP resetflag4_snd_ex_pend_dyna[];
extern const CALLOUTFP callout_netorder_snd_ex_trig_norm[];
extern const CALLOUTFP callout_cpuorder_snd_ex_trig_norm[];
extern const CALLOUTFP callout_netorder_snd_ex_pend_norm[];
extern const CALLOUTFP callout_cpuorder_snd_ex_pend_norm[];
extern const CALLOUTFP callout_netorder_snd_ex_trig_zero[];
extern const CALLOUTFP callout_cpuorder_snd_ex_trig_zero[];
extern const CALLOUTFP callout_netorder_snd_ex_trig_dyna[];
extern const CALLOUTFP callout_cpuorder_snd_ex_trig_dyna[];
extern const CALLOUTFP callout_netorder_snd_ex_pend_dyna[];
extern const CALLOUTFP callout_cpuorder_snd_ex_pend_dyna[];
extern MessageIdentifier sndlist_snd_in_norm_SendMsg[];
extern MessageIdentifier *sndlist_snd_in_norm[];
extern MessageIdentifier *sndlist_snd_in_zero[];
extern UINT8 bitorder_snd_ex_trig_norm[];
extern UINT8 bitorder_snd_ex_pend_norm[];
extern UINT8 bitorder_snd_ex_trig_dyna[];
extern UINT8 bitorder_snd_ex_pend_dyna[];
extern CANType can_id_snd[];
extern UINT8 can_type_snd[];
extern CANType can_id_rcv[];
extern UINT8 can_type_rcv[];
extern UINT8* const ulpdu_rcv_buf_addr[];
extern UINT8 ulpdu_rcv_dlc[];
extern UINT8 *msgbuf_snd_ipdu[];
extern UINT8 *msgbuf_rcv_ipdu[];
extern UINT8 tnum_snd_ipdu ;
extern UINT8 tnum_rcv_ipdu ;
extern MessageIdentifier *sndlist_snd_ipdu[];
extern MessageIdentifier *sndlist_rcv_ipdu[];
extern UINT32 bitsize_snd_ipdu[];
extern UINT32 bitsize_rcv_ipdu[];
extern UINT32 bytesize_snd_ipdu[];
extern UINT32 bytesize_rcv_ipdu[];
extern UINT64 timeperiod_snd_ipdu[];
extern UINT64 timeoffset_snd_ipdu[];
extern UINT64 delaytime_snd_ipdu[];
extern UINT64 timeout_snd_ipdu[];
extern UINT64 timeout_rcv_ipdu[];
extern UINT64 firsttimeout_snd_ipdu[];
extern UINT64 firsttimeout_rcv_ipdu[];
extern const CALLOUTFP callout_snd_ipdu[];
extern const CALLOUTFP callout_rcv_ipdu[];
extern char *layerused_snd_ipdu[];
extern char *layerused_rcv_ipdu[];
extern UINT8 transmode_snd_ipdu[];
extern UINT32 msgbuf_snd_tmp[];
extern UINT32 msgbuf_snd_after_swapbytes[];
extern UINT32 bytesize_snd_max ;
extern UINT32 ipdubuf_rcv_tmp[];
extern UINT32 msgbuf_rcv_after_swapbytes[];
extern UINT32 msgbuf_rcv_ipdu_tmp[];
extern UINT32 bytesize_rcv_max ;
extern UINT8 flg_snd_ipdu[];
extern TimerType timer_snd_ctrl[];
extern TimerType timer_snd_periodic[];
extern TimerType timer_rcv_ctrl[];
extern UINT8 tnum_timer ;
extern TickCounterType timinib_tickid[];
extern TimerType timcb_next[];
extern TimerType timcb_prev[];
extern TimerTickType timcb_timval[];
extern TimerTickType timcb_cycle[];
extern const TIMFP timcb_cback[];
extern UINT16 timcb_param[];
extern ULSndFunc snd_ul_func[];
extern ULSndCancelFunc snd_cancel_ul_func[];
extern ULRcvFunc rcv_ul_func[];
extern LINType lin_id_snd[];
extern UINT8 lin_type_snd[];
extern LINType lin_id_rcv[];
extern UINT8 lin_type_rcv[];
extern MessageIdentifier *sndlist_rcv_ipdu_norm[];
extern MessageIdentifier sndlist_rcv_ipdu_zero[];
extern MessageIdentifier *sndlist_rcv_ipdu_dyna[];
extern UINT8 bitorder_rcv_ipdu_norm[];
extern UINT8 bitorder_rcv_ipdu_dyna[];
extern UINT32 bitsize_rcv_ipdu_norm[];
extern UINT32 bitsize_rcv_ipdu_dyna[];
extern UINT32 bytesize_rcv_ipdu_norm[];
extern UINT32 bytesize_rcv_ipdu_dyna[];
extern UINT32 offset_rcv_ipdu_norm[];
extern UINT32 offset_rcv_ipdu_dyna[];
extern UINT8 byteorder_rcv_ipdu_norm[];
extern const CALLOUTFP callout_netorder_rcv_ipdu_norm[];
extern const CALLOUTFP callout_cpuorder_rcv_ipdu_norm[];
extern const CALLOUTFP callout_netorder_rcv_ipdu_zero[];
extern const CALLOUTFP callout_cpuorder_rcv_ipdu_zero[];
extern const CALLOUTFP callout_netorder_rcv_ipdu_dyna[];
extern const CALLOUTFP callout_cpuorder_rcv_ipdu_dyna[];

